- name: Demo of the variab le  
  hosts: all 
  vars:
    URL: test.google.com
  vars_files:
    - dev-vars.yml
  vars_prompt:
    - name : URLName
      prompt: enter the user name
      private: no
  tasks:
    - name: Printing Global URL
      ansible.builtin.debug:
        msg: value of the URL is  {{ URL }}

    - name: Printing local variable
      vars:
        URL: local.google.com
      ansible.builtin.debug:
        msg: value of the URL is  {{ URL }}
    
    - name: Printing prompt variable
      ansible.builtin.debug:
        msg: value of the URL is  {{ URLName }}
