- name: Demo on Register
  hosts: all 

  tasks:
    - name: Printing Global URL
      ansible.builtin.shell: uptime
        Register: OUT
    - name: Priniting the OUT variable
      ansible.builtin.debug:
        msg: registered variable value {{OUT.stdout}}

    - name: Declaring the variable
      set_fact:
        STATUSCODE: "{{OUT.rc}}"
    
    - name: Printing the setfact
      ansible.builtin.debug:
        msg: registered variable value {{ STATUSCODE }}